version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: smallbang-memcached

    redis:
      image: redis:alpine
      container_name: smallbang-redis

    webserver:
      image: nginx:alpine
      container_name: smallbang-webserver
      working_dir: /src
      volumes:
          - ./src:/src
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9999:80"

    php-fpm:
      build: php-fpm
      container_name: smallbang-php-fpm
      working_dir: /src
      volumes:
        - ./src:/src
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

